"""add indexes and unique source url

Revision ID: 9fb12f376407
Revises: ae3f54b8147e
Create Date: 2026-06-08 18:24:38.409020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb12f376407'
down_revision: Union[str, None] = 'ae3f54b8147e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_logs_stage'), ['stage'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_news_id'), ['news_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_status'), ['status'], unique=False)

    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_enabled'), ['enabled'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_sources_url'), ['url'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_sources_url'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_sources_enabled'))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_status'))
        batch_op.drop_index(batch_op.f('ix_posts_news_id'))

    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_logs_stage'))
        batch_op.drop_index(batch_op.f('ix_error_logs_created_at'))

    # ### end Alembic commands ###
